name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
  
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    steps:
    - uses: actions/checkout@v2     
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
   
    - name: Login To Registry
      uses: docker/login-action@v2.1.0
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.6.0

    - name: Build message Image
      working-directory: ./
      run: docker build -t ${{secrets.DOCKER_USER}}/messagemicroservice:v1 .

    - name: Push message Image
      working-directory: ./
      run: docker push ${{secrets.DOCKER_USER}}/messagemicroservice:v1
    
