name: SonarCloud
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2     
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    
    
    - name: Cache maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
      
    - name: Build with Maven
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B package verify sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=CrookedDreamRealm_micro_messages -Dsonar.organization=dreamrealm2
