name: SonarCloud
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run:
          mvn verify sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=dreamrealm2 \
          -Dsonar.projectKey=CrookedDreamRealm_micro_messages \
          -Dsonar.source=. \
          -Dsonar.projectBaseDir=\
